### ISSUE TITLE
Create a flyer "Call for Volunteers"

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2023-tasks#1]

**Comment by inovizz** [comment]
@snehithallamraju - Can't assign but tagging you here.

**Comment by snehithallamraju** [comment]
![PyCon CFP](https://user-images.githubusercontent.com/20667307/229016082-97785574-5123-4998-839e-11d2be1972cf.png)

**Comment by snehithallamraju** [comment]
Flyer created
