### ISSUE TITLE
Invite Volunteers to Respective streams in Zulip

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2023-tasks#10]
- [ ] @kalyan678 to send emails to all volunteers mentioning Zulip streams and ask them to join respective streams

Here are the invite links - 

Review(CFP) - https://pyconindia.zulipchat.com/join/ouroqnkry7mjpajmxgbvolfy/
Technology - https://pyconindia.zulipchat.com/join/uzub5sbqhlusl6fz4wxy75ln/
Promotions - https://pyconindia.zulipchat.com/join/xcmsnyr2cwfiq6a2mztatlvm/
Mentorship - https://pyconindia.zulipchat.com/join/xulpcaewna6cnxwbczgpoe66/
Diversity - https://pyconindia.zulipchat.com/join/a7z54h4pngcny3azat4c7jg2/
Design  - https://pyconindia.zulipchat.com/join/6ozmknokzh4y4zjxj5zwdr3e/
Content - https://pyconindia.zulipchat.com/join/xgtmxqfy3sm6okkkolfmva5v/

**Comment by inovizz** [comment]
`Hi there,

We hope this email finds you well. We are writing to thank you for offering your help and support as a volunteer for PyCon India 2023. Your willingness to volunteer is greatly appreciated, and we are excited to have you as part of our team.

We would like to inform you that workgroup formation has started, and we are in the process of choosing workgroup leads. We request all volunteers to join the respective workgroup streams they would like to help us with. Your contribution will help us make PyCon India 2023 a successful event.

Below are the invite links for each workgroup:

Review(CFP) - https://pyconindia.zulipchat.com/join/ouroqnkry7mjpajmxgbvolfy/
Technology - https://pyconindia.zulipchat.com/join/uzub5sbqhlusl6fz4wxy75ln/
Promotions - https://pyconindia.zulipchat.com/join/xcmsnyr2cwfiq6a2mztatlvm/
Mentorship - https://pyconindia.zulipchat.com/join/xulpcaewna6cnxwbczgpoe66/
Diversity - https://pyconindia.zulipchat.com/join/a7z54h4pngcny3azat4c7jg2/
Design - https://pyconindia.zulipchat.com/join/6ozmknokzh4y4zjxj5zwdr3e/
Content - https://pyconindia.zulipchat.com/join/xgtmxqfy3sm6okkkolfmva5v/

Please click on the links above to join the respective workgroup streams. If you are unsure about which workgroup to join, feel free to get in touch with us for further guidance.

Regarding Sponsorship and any other workgroup which you don't see here, we'll reach out separately to you.

Thank you once again for your support and commitment to PyCon India 2023. We look forward to working with you and making this event a huge success.

Best regards,
PyCon India 2023 organizing team`

**Comment by kalyan678** [comment]
@inovizz - Thanks Sanchit for the draft. Email sent to all the volunteers!
