### ISSUE TITLE
Draft an email for Keynote Invitation

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2023-tasks#13]

**Comment by inovizz** [comment]
cc @soumendrak

**Comment by Niveshkrishna** [comment]
Subject: Invitation to be a Keynote Speaker at PyCon India 2023

Dear [Speaker's Name],

We are thrilled to invite you as a keynote speaker at PyCon India 2023, which marks the 14th edition of the conference. As one of the most prestigious conferences in India for Python enthusiasts, we believe your insights and expertise would make a great contribution to our event.

PyCon India has been a hub for Python enthusiasts, developers, and technologists to come together, learn, network, and share their experiences. Our event attracts professionals and enthusiasts from all over the world, making it an excellent opportunity for speakers to share their thoughts, learn from the community, and build new connections.

The event is scheduled to take place in Hyderabad, India from 30th September to 1st October, and we anticipate over 1,000 attendees. As a keynote speaker, you will have the opportunity to speak to a broad audience of technologists, developers, and enthusiasts interested in your topic.

We are looking for insightful and engaging talks on Python and its applications. If you are interested in joining us as a keynote speaker, please let us know by [date]. Also, kindly include your bio, talk abstract, and any relevant details that you think would help us understand your proposed topic better.

We look forward to hearing from you soon and hope you will be able to join us for PyCon India 2023.

Best regards,
PyCon India 2023 Organizing Committee


@inovizz @soumendrak Please suggest any corrections

**Comment by soumendrak** [comment]
Thanks, @Niveshkrishna 

I have slightly modified the draft. Please have a look:

Subject: Invitation to be a Keynote Speaker at PyCon India 2023

Dear [Speaker's Name],
We are thrilled to invite you as a keynote speaker at PyCon India 2023, which marks the 14th edition of the conference as one of the most prestigious conferences in India for Python enthusiasts, your insights and expertise would significantly contribute to our event.

PyCon India has been a hub for Python enthusiasts, developers, and technologists to come together, learn, network, and share their experiences. In addition, our event attracts professionals and enthusiasts worldwide, making it an excellent opportunity for speakers to share their thoughts, learn from the community, and build new connections.

The event will occur in Hyderabad, India, **from 30th September to 1st October**, and we anticipate over 1,000 attendees. As a keynote speaker, you can speak to a broad and diverse audience of technologists, developers, and enthusiasts interested in your topic.

We are looking for insightful and engaging talks on Python and its applications. If you are interested in joining us as a keynote speaker, please let us know by [date]. Also, could you include your bio, talk abstract, and relevant details to help us better understand your proposed topic?

We look forward to hearing from you soon and hope you will be able to join us for PyCon India 2023.

Best regards,
PyCon India 2023 Organizing Committee
https://in.pycon.org/2023

**Comment by inovizz** [comment]
Please copy the email in this folder as well for future reference.

https://drive.google.com/drive/u/0/folders/1cxMyb9umqKhnun0oibFwNgV-cZMoE4Gh
