### ISSUE TITLE
Create a "How to Volunteer Guide"

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2023-tasks#18]
Lot of folks reached out asking how to volunteer and how to navigate Zulip. We need a guide on this ASAP.

Please create a detailed guideline on Github may be as a README file or Wiki and we'll pin it on all social channels including Website, Mailing Lists, and Zulip. 

Few refs of such requests:

1. 
![Image](https://user-images.githubusercontent.com/3849885/232307085-3400a77e-673b-4e61-98e2-6bb9cd110591.png)

2. 
![Image](https://user-images.githubusercontent.com/3849885/232307099-fcb62ae2-cb46-4cac-812c-fc70b2327456.png)

**Comment by bkamapantula** [comment]
Documenting some Volunteer FAQs here:

1. Where can I contribute?
 - Review the list of Zulip workstreams for different WorkGroups (WGs) [here](https://pyconindia.zulipchat.com/#narrow/stream/381468-2023.2Fannouncements/topic/PyCon.20India.202023/near/350313376).
2. How many WGs can I contribute?
  - If it's your first time, try to focus on no more than two WGs.
3. When do I get started?
  - Please join your interested WGs and wait patiently. We've just kicked off the work, different WGs kick-off work at different times.
5. When is the conference?
  - 29 September to 2 October

**Comment by soumendrak** [comment]
Adding to number, 5
6. What is the basic schedule of the conference i.e. when is the DevSprint, Conference, and Workshop?

**Comment by realslimshanky** [comment]
I'll be reviewing the last 2 blogs on the same topic and get back with a new draft.
- https://in.pycon.org/blog/2020/2020-call-for-volunteers.html
- https://in.pycon.org/blog/2021/call-for-volunteers.html

**Comment by realslimshanky** [comment]
Hey Sanchit, I'm not able to make time this so I'm unassigning myself and hading over to Content lead.

**Comment by inovizz** [comment]
@realslimshanky - no problem at all Shashank.

**Comment by inovizz** [comment]
Can you folks review this?

https://deploy-preview-412--serene-souffle-d67037.netlify.app/

**Comment by inovizz** [comment]
https://github.com/pythonindia/inpycon-blog/pull/412

https://deploy-preview-412--serene-souffle-d67037.netlify.app/

**Comment by bkamapantula** [comment]
Reviewed the [volunteer blog entry](https://deploy-preview-412--serene-souffle-d67037.netlify.app/2023/volunteering-guide-pyconin23.html).

- Reads great.
- Highlights what new volunteers can do to get started.
- Links work.

Couple of suggestions:
- please add a link to [R&D Zulip WG](https://pyconindia.zulipchat.com/#narrow/stream/389199-wg.2Fr.26d).
- for sponsorship, we can link Snehith's personal Zulip DM link.

**Comment by inovizz** [comment]
Thanks Bhanu, addressed your comments here - https://deploy-preview-412--inpyconblog.netlify.app/2023/volunteering-guide-pyconin23.html
