### ISSUE TITLE
Send a Thank you Note on social channels for Keynote Suggestions

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2023-tasks#19]
Send thank you note on -

- inpycon mailing list
- twitter
- linkedin
- facebook
- instagram

**Comment by bpkapkar** [comment]
Thanking for Keynote Speaker Suggestions post is out on our social media platforms. Help spread the word by liking and retweeting.
Below are the post links:
Twitter - https://twitter.com/pyconindia/status/1648640419029458944?t=4t8QYXXcm2RzVsSzfL0X8A&s=19
LinkedIn - https://www.linkedin.com/posts/pyconindia_pyconindia2023-pyconindia2023-hyderabad-activity-7054407186373873665-BqlZ?utm_source=share&utm_medium=member_android
Facebook - https://www.facebook.com/133849919970392/posts/pfbid0ARJ9KqiRy5yi4fftrAhvAKekXHzD51aFrXWy2he1gQUTatkj52jSeEpd6G2zTN3wl/?mibextid=Nif5oz
Instagram - https://www.instagram.com/p/CrNxhxdrZ09/?igshid=YmMyMTA2M2Y=
