### ISSUE TITLE
Send a Thank you Note on social channels for Volunteer Registration

### ISSUE THREAD

**Issue by bpkapkar** [pythonindia/inpycon2023-tasks#21]
Send thank you note  for volunteer registration on 
Design Team  - Will create the poster 
SM Team will have below task:
inpycon mailing list- draft a  mail

Write a tweet/message for social media handles post along with poster on below channels:
twitter 
linkedin
facebook
instagram

**Comment by kalyan678** [comment]
I think we are good to close this issue. Thanks!

**Comment by bpkapkar** [comment]
Closing the issue as per the discussion. As we are good on it.
