### ISSUE TITLE
CFP Announcement

### ISSUE THREAD

**Issue by bpkapkar** [pythonindia/inpycon2023-tasks#22]
- [x] @iamaravindsekar to get the flyer ready by EOD 18th May (including feedback iterations)
- [x] @Sc0rpi0n101 to get an email template ready for mailing list announcements by 21st May
- [x] @bpkapkar to get the content ready by EOD 18th May for SM posts
- [x] @soumendrak & @ananyo2012 to validate if everything is fine with Junction
- [x] @bpkapkar & @Amritha-Madam to announce CFP on social media at 10:00 am 22nd May
- [x] @inovizz to send an email on the mailing list announcing CFP

**Comment by bpkapkar** [comment]
@iamaravindsekar  @soumendrak @Amritha-Madam  This design need to get ready as CFP  will get open mid of next week.

**Comment by iamaravindsekar** [comment]
The Call for CFP images can be found here,
https://drive.google.com/drive/folders/1LCr8qQe4XPYj3lQKSjFGHZxR2ucqgHr8

**Comment by Sc0rpi0n101** [comment]
```
Hi everyone, 

As you might know, we're back with PyCon India[1] as an in-person conference this year. 

PyCon India 2023 will take place from September 29 - October 2 in Hyderabad, with the main conference on September 30 and October 1, workshops on September 29, and DevSprints on October 2. 


With that said, our Call for Proposals is now open[2]. Here are some important details about the CFP:
- We'll be opening the CFP from today, May 22, 2023.
- The last date to submit CFP will be August 5, 2023.
- The final agenda will be published on September 3, 2023.
- We will also have rehearsal talks to prepare speakers and content, details of which will be discussed later and announced
accordingly.

If you've any doubts or thoughts regarding the above, please feel free to
respond here or reach out to any of us on [Zulip][3] #2023/discussion
stream.

We look forward to all your support in making this year's PyCon India a
grand success.

[1]: https://in.pycon.org/2023/
[2]: https://in.pycon.org/cfp/pycon-india-2023/proposals/
[3]: https://pyconindia.zulipchat.com/#narrow/stream/381469-2023.2Fdiscussions
```

Please review @inovizz @bpkapkar

**Comment by inovizz** [comment]
thanks everyone for your support.
