### ISSUE TITLE
Create a video - PyCon is back after 4 year in-person conferences with a few PyCon 2019 media

### ISSUE THREAD

**Issue by bpkapkar** [pythonindia/inpycon2023-tasks#23]
Design Team - Will create the video 

SM Team will have below task:
Write a tweet/message for social media handles post along with poster on below channels:
twitter
linkedin
facebook
instagram

**Comment by bpkapkar** [comment]
@iamaravindsekar  Requesting you to please have look into and please update the progress. Is any volunteer working on it.

**Comment by iamaravindsekar** [comment]
First version of the poster is here...
Attached the edit url from Canva..
https://www.canva.com/design/DAFgiPe8wbo/0dSHGuDxDPYWvtIv_gUGKQ/edit?utm_content=DAFgiPe8wbo&utm_campaign=designshare&utm_medium=link2&utm_source=sharebutton

**Comment by iamaravindsekar** [comment]
![PyconIndia 2023 is offline](https://user-images.githubusercontent.com/20441340/236642892-b78a7e7f-2151-4e4b-a876-fb37e94d7c14.png)

**Comment by iamaravindsekar** [comment]
Inputs from various folks..
@abhishekmishragithub - Looks too congested and bit of spacing is needed before subtitle, Pycon header title can be a bit bold.
@bhanuvrat @kalyan678 Pycon India should be PyCon India, adding the text "again" can be great here.
@inovizz there are too much content on the poster and this can be simplified.

**Comment by iamaravindsekar** [comment]
![PyconIndia 2023 is offline](https://user-images.githubusercontent.com/20441340/236645519-e01a31cd-8cea-43d5-b564-d3edd0f66109.png)

**Comment by kalyan678** [comment]
@bpkapkar / @Amritha-Madam I believe we are good to close this issue right?
