### ISSUE TITLE
Create event on LinkedIn, Facebook, and Meetup

### ISSUE THREAD

**Issue by bpkapkar** [pythonindia/inpycon2023-tasks#27]
Description:
As part of our social media strategy, we need to create an event on LinkedIn, Facebook, and Meetup to promote our upcoming Pyconindia launch.

Tasks:

Create a draft of the event post for each platform and review with the team
Once approved, create the event on LinkedIn, including the event title, date, time, location, and a brief description
Create the event on Facebook, including the event title, date, time, location, and a brief description
Create the event on Meetup, including the event title, date, time, location, and a brief description
Publish the events on each platform
Share the events on our company's social media accounts

**Comment by iamaravindsekar** [comment]
@bpkapkar Is this done? What would you need from design team to get this done?

**Comment by bpkapkar** [comment]
@iamaravindsekar  Its not yet done, once we have venue and event details finalize we will create the placeholder. in linked and Facebook and other platforms so it will act as reminder of event and share the details of event. This Poster more of event brief details like venue , dates , pyconlogo , may be key notes speakers. If the poster is ready well in advance that will be helpful. @Amritha-Madam

**Comment by bpkapkar** [comment]
Events are created on facebook , linkedin and meetup page as place holder.

https://fb.me/e/2OjPCVxCp

Checkout this Meetup with Hyderabad Python User Group: https://meetu.ps/e/MjkVQ/M7kcz/i
