### ISSUE TITLE
Make CFP announcement

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2023-tasks#28]
- [ ] Create a flyer
 - [ ] Make social media posts
 - [ ] Announce on the mailing list

**Comment by inovizz** [comment]
@soumendrak  - can you take lead on this task?

**Comment by bpkapkar** [comment]
@inovizz @soumendrak  This task was already created https://github.com/orgs/pythonindia/projects/3?pane=issue&itemId=26122008. As it was created for demo purpose, should we use old one or use this one . One of this issue need to deleted as its duplicate.

**Comment by khushal786** [comment]
Can I know in detail what we have to create and can I content for same

**Comment by inovizz** [comment]
> @inovizz @soumendrak This task was already created https://github.com/orgs/pythonindia/projects/3?pane=issue&itemId=26122008. As it was created for demo purpose, should we use old one or use this one . One of this issue need to deleted as its duplicate.

Sure, feel free to close the task if there is a duplicate already.

**Comment by bpkapkar** [comment]
Closing the task as its Duplicate task to https://github.com/pythonindia/inpycon2023-tasks/issues/22 @khushal786  please do have look on the github link , will discuss more on that . Please do post your query there , will guide you on it
