### ISSUE TITLE
Create guide for good proposal

### ISSUE THREAD

**Issue by Niveshkrishna** [pythonindia/inpycon2023-tasks#29]
Need to create a guide about what a good proposal is and what a bad proposal is. We can take previous proposals which were accepted as examples and explain why they were selected. 

This has to be ready before we make CFP live

/cc @inovizz @soumendrak

**Comment by bkamapantula** [comment]
@soumendrak created it: https://github.com/pythonindia/junction/wiki/Speaker-best-practices

Closing this.
