### ISSUE TITLE
Create a post to invite volunteers to join Design WG

### ISSUE THREAD

**Issue by realslimshanky** [pythonindia/inpycon2023-tasks#32]
Due to mistake, we didn't add Design WG in our volunteer form. This is now fixed and we need to reach out to social media inviting people interested in Design to volunteer. Updated volunteer form - https://forms.gle/Ep8HtebivjhhhjXh7

**Comment by bpkapkar** [comment]
We had good numbers of the volunteer, in the form response . I have shared the details for the same, so we are good to close this issue. In case we have shortfalls for the volunteer , please create the new issue will plan accordingly.
