### ISSUE TITLE
Announce PyCon India Logo

### ISSUE THREAD

**Issue by bpkapkar** [pythonindia/inpycon2023-tasks#34]
Task Description: The PyCon India organizing team has finalized the logo for this year's conference and we need to announce it to the community. The announcement should include the new logo and a brief description of the inspiration behind it.

Task Steps:

Obtain the finalized PyCon India logo from the organizing team.
Create an announcement post on the PyCon India website, social media accounts (e.g., Twitter, Facebook, LinkedIn), and other relevant channels.
Include the new logo in the announcement post.
Write a brief description of the inspiration behind the logo. This could include the design elements, color choices, and any other relevant details.
Share the announcement post with the PyCon India community and encourage them to share it with their networks.

**Comment by gargi-04** [comment]
This task is completed I think, should we close it?

**Comment by bpkapkar** [comment]
@gargi-04  We are good to close this issue , just add the links for social media post and close it.

**Comment by gargi-04** [comment]
The logo has been announced on SM.
Facebook - https://www.facebook.com/133849919970392/posts/pfbid048suSUUKuEL25kbVFi882mc4tKy9jUY1mo18gX48CeQZ5R3eAWKMVwJmPHVfEheWl/?mibextid=Nif5oz

Instagram - https://www.instagram.com/p/CsXwIwLrm-Y/?igshid=MTc4MmM1YmI2Ng==

Linkedin - https://www.linkedin.com/posts/pyconindia_hyderabad-pyconindia2023-pycon-activity-7064813074687397888-O9JQ?utm_source=share&utm_medium=member_android

Twitter - https://twitter.com/pyconindia/status/1659048039259185152?t=zMNkqer3wEJnAvGI8pV7Bw&s=19

**Comment by gargi-04** [comment]
closes #34

**Comment by bpkapkar** [comment]
Thanks @gargi-04  for sharing the link , closing the issue as its completed.
