### ISSUE TITLE
Promote blog post on "How to Volunteer" on Social Media Handles

### ISSUE THREAD

**Issue by bpkapkar** [pythonindia/inpycon2023-tasks#38]
The purpose of this task is to generate awareness and engagement for the blog post titled "How to Volunteer" by promoting it on the company's social media handles. By leveraging social media platforms, we aim to reach a wider audience and encourage them to read and share the blog post

Task Details:

Task Type: Social Media Promotion ,  Flyer Creation for the same 
Assignee: Communication Team and Design Team
Priority: High
Due Date: 23 -05 -2023

Additional Notes:
Consider using relevant hashtags, such as #volunteering, #communityengagement, or #socialimpact, to increase the visibility of the social media posts. Collaborate with the design team if any custom graphics or visuals are required for the social media promotion

**Comment by iamaravindsekar** [comment]
@bpkapkar @Amritha-Madam where can I find the content for this post?

**Comment by bpkapkar** [comment]
@iamaravindsekar You can take reference from this https://in.pycon.org/blog/2023/volunteering-guide-pyconin23.html . To get started , hopefully this will help out. We will try to provide the content going forward, feel  free to add and delete content on flyers as we (@Amritha-Madam) are flexible on creativity. When can we expect the flyer as post is waiting for it.

**Comment by iamaravindsekar** [comment]
I am planning to do ti this way... 
(Header line) How to Volunteer for pyconIndia 2023?
(Body) Three steps 1--->2--->3 and need content for these 3 steps, something short and sweet.. for the stepper.
(Footer) Benifits of volunteering

I thought of putting [1] Choose your WG of interest [2] Submit the form and get onboarded [3] Join us on zuilip, contribute to your WG and join our weekly WG calls

Please help me with the content for this 3 steps alone.. We can get this post up by today evening...

@bpkapkar @Amritha-Madam

**Comment by iamaravindsekar** [comment]
url for the image for social media posts ..
@bpkapkar 

https://drive.google.com/file/d/1tl54t2NXpUft6yTan81vWWRg8uJftmyf/view?usp=share_link

**Comment by bkamapantula** [comment]
This looks good, Aravind.

**Comment by bpkapkar** [comment]
Thanks @iamaravindsekar  @Amritha-Madam for your support , as we have completed this request closing it.

Hello All, "How to Volunteer" blog post announcement is done on all our SM channels. Help spread the word by liking and retweeting.
Twitter - https://twitter.com/pyconindia/status/1663044100042670081?t=5fho7nt-sQOZbznNkUAxhw&s=19
LinkedIn - https://www.linkedin.com/posts/pyconindia_pyconindia-volunteering-communityservice-activity-7068811424000602112-Isx-?utm_source=share&utm_medium=member_android
Facebook - https://m.facebook.com/story.php?story_fbid=pfbid0ABENSPtwYhh9FboAj9am2yDk3Ms6KZmozjro3FyTVKM36KU2X8bkbusepMmskzjKl&id=133849919970392&mibextid=Nif5oz
Instagram - https://www.instagram.com/p/Cs0IUmJtPqY/?igshid=MzRlODBiNWFlZA==

[PyCon India 2023 on LinkedIn: #pyconindia #volunteering #communityservice](https://www.linkedin.com/posts/pyconindia_pyconindia-volunteering-communityservice-activity-7068811424000602112-Isx-?utm_source=share&utm_medium=member_android)
🤝 Want to make a difference and give back to your community? Check out the comprehensive guide on "How to Volunteer for PyConIndia" and discover various…
[PyCon India on Instagram: "🤝 Want to make a difference and give back to your community? Check out the comprehensive guide on "How to Volunteer for PyConIndia" and discover various opportunities, tips on finding the right work group, and how to make the most impact. Check out the link in the bio. #pyconindia2023 #pyconindia #volunteering #communityservice"](https://www.instagram.com/p/Cs0IUmJtPqY/?igshid=MzRlODBiNWFlZA==)
1 likes, 0 comments - PyCon India (@__pyconindia__) on Instagram: "🤝 Want to make a difference and give back to your community? Check out the comprehensive guide..."
