### ISSUE TITLE
Send a post for Keynote Suggestions

### ISSUE THREAD

**Issue by inovizz** [pythonindia/inpycon2023-tasks#4]
- [x] @snehithallamraju to create flyer
- [ ] @bpkapkar to post on social media

**Comment by snehithallamraju** [comment]
attached flyer ![keynote](https://user-images.githubusercontent.com/20667307/230581168-ff365c44-fd81-4e3f-bc6d-09ab62d1f504.png)

**Comment by snehithallamraju** [comment]
Modified version with link updated to shortened link

![keynote_2](https://user-images.githubusercontent.com/20667307/230598449-82967e56-7b55-47f1-b741-6c7e1dbeb460.png)

**Comment by bpkapkar** [comment]
Its has been posted on below social media.

Instagram - https://www.instagram.com/p/CqvAhVkBPDE/?utm_source=ig_web_copy_link

twitter - https://twitter.com/pyconindia/status/1644301767939866625?t=OCXThnvOyW0aHXL3v8qY5w&s=19

Linkedin - https://www.linkedin.com/feed/update/urn:li:activity:7050078543464050690
