### ISSUE TITLE
Promote Blog Post on "A Guide to Speaking at PyCon India" on Social Media Handles

### ISSUE THREAD

**Issue by shlokashah** [pythonindia/inpycon2023-tasks#43]
The purpose of this task is to generate awareness and engagement for the blog post titled "A Guide to Speaking at PyCon India" by promoting it on our social media handles. By leveraging social media platforms, we aim to reach first-time speakers as well as others and encourage them on submitting a CFP at PyCon India. The blog post provides a list of things one should take care of when submitting a CFP.

**Task Details:**

**Blog Link:** https://in.pycon.org/blog/2023/guide-to-speaking.html
**Task Type:** Social Media Promotion, Flyer Creation for the same
**Assignee:** Communication Team and Design Team
**Priority:** High
**Due Date:** 24-05-2023

**Additional Notes:**
Consider using relevant hashtags, such as #speaking, #first-time-speakers, #cfp, and #cfpguidelines to increase the visibility of the social media posts. Collaborate with the Design team if any custom graphics or visuals are required for the social media promotion

**Comment by Chidu2000** [comment]
Is the issue still open

**Comment by iamaravindsekar** [comment]
This is done and please close thus whenever you want.. Thank you..
 @bkamapantula @Amritha-Madam
