### ISSUE TITLE
Community Partner Program Launch Announcement

### ISSUE THREAD

**Issue by bpkapkar** [pythonindia/inpycon2023-tasks#49]
Summary:
Create announcement for Community Partner Program launch.

Description:
Craft concise announcement to introduce and promote Community Partner Program. Design visually appealing assets. Gather feedback, obtain approval, and publish on  LinkedIn, Facebook, Instagram and twitter  channels for community engagement.

Acceptance Criteria:

- Clear and engaging announcement message.
- Visually appealing design assets.
- approval obtained.

Notes:

Collaborate with design team for flyer.
Encourage community participation

**Comment by khushal786** [comment]
@iamaravindsekar Sir can you guide me with this so I can work on it

**Comment by bpkapkar** [comment]
Hello everyone, Community Partner post is now out on all of our SM channels. Do spread the word by liking and retweeting.

Twitter - https://twitter.com/pyconindia/status/1678245381405310976?t=pJuOhkpWGdnaKrZGWp3DAA&s=19

LinkedIn - https://www.linkedin.com/posts/pyconindia_pyconind2023-activity-7084011565603061760-cltf?utm_source=share&utm_medium=member_android

Facebook - https://m.facebook.com/story.php?story_fbid=pfbid0N1y51UDEUAjoAhdf1iG6wGAT2dJjUUrsjkETBqtTLnkqcef2N8tC2MM9Hd5skTTCl&id=100064696716190&mibextid=Nif5oz

Instagram - https://www.instagram.com/p/CugIKWdPBk0/?igshid=MzRlODBiNWFlZA==

[PyCon India 2023 on LinkedIn: #pyconind2023](https://www.linkedin.com/posts/pyconindia_pyconind2023-activity-7084011565603061760-cltf?utm_source=share&utm_medium=member_android)
📢 Attention all communities! Be a partner of PyCon India 2023, the ultimate Python conference! Expand your network, exchange knowledge, and grow together…

**Comment by bpkapkar** [comment]
Completed
