### ISSUE TITLE
Creative + Announce Call for Sponsors on Social Media

### ISSUE THREAD

**Issue by snehithallamraju** [pythonindia/inpycon2023-tasks#54]
Create a poster to announce the call for sponsors for PyConIndia 2023 on social media channels.

Content can be as below

Call for Sponsors for 🐍 #PyConIndia2023 is open. 

Sponsors help make the conference run smoothly and help providing a great experience for everyone. 

Interested in sponsoring the conference and giving back to the community? Check out our sponsorship prospectus at https://in.pycon.org/2023#sponsors

Tentative announce date : 23-JUN-2023

**Comment by iamaravindsekar** [comment]
Please use this image... Thank you :)
 https://drive.google.com/file/d/1qHOgmn6_ESyMjY1z3ZlkM_GFCGZz8LTM/view?usp=share_link
