### ISSUE TITLE
Launch of Community Partner program

### ISSUE THREAD

**Issue by Niveshkrishna** [pythonindia/inpycon2023-tasks#56]
- [x] Finish ppt and create pdf version of it
- [x] Add a section in website for community program
- [x] Prepare flyers for social media announcement
- [ ] Prepare a blog about highlights of the program

**Comment by bpkapkar** [comment]
Hello everyone, Community Partner post is now out on all of our SM channels. Do spread the word by liking and retweeting.

Twitter - https://twitter.com/pyconindia/status/1678245381405310976?t=pJuOhkpWGdnaKrZGWp3DAA&s=19

LinkedIn - https://www.linkedin.com/posts/pyconindia_pyconind2023-activity-7084011565603061760-cltf?utm_source=share&utm_medium=member_android

Facebook - https://m.facebook.com/story.php?story_fbid=pfbid0N1y51UDEUAjoAhdf1iG6wGAT2dJjUUrsjkETBqtTLnkqcef2N8tC2MM9Hd5skTTCl&id=100064696716190&mibextid=Nif5oz

Instagram - https://www.instagram.com/p/CugIKWdPBk0/?igshid=MzRlODBiNWFlZA==

[PyCon India 2023 on LinkedIn: #pyconind2023](https://www.linkedin.com/posts/pyconindia_pyconind2023-activity-7084011565603061760-cltf?utm_source=share&utm_medium=member_android)
📢 Attention all communities! Be a partner of PyCon India 2023, the ultimate Python conference! Expand your network, exchange knowledge, and grow together…
