### ISSUE TITLE
Announcement for Python Express

### ISSUE THREAD

**Issue by bkamapantula** [pythonindia/inpycon2023-tasks#58]
Can we please make an announcement about Python Express in our channels? I've already [announced](https://mail.python.org/pipermail/inpycon/2023-June/013354.html) on the PyCon India mailing list.

> We are happy to announce the revival of @pythonexpress, an initiative of @pyconindia [RELEVANT SM HANDLE], to connect colleges interested in hosting Python workshops with working professionals from the industry.
> 
> Join the wait list to know about the updates: https://pythonexpress.org/

More information, use as needed:

> On Python Express, learners or faculty can register to host workshops at educational institutions and trainers can sign-up to mentor the learners in the workshops. The workshops are offered at free cost to the learners.
> 
> Trainers will undergo training using carefully curated content developed by the experienced Python Express Team.

Python Express doesn't have any presence on any social media channels **except Twitter** (`@pythonexpress`). We can have a poster for the full site launch later, not required now.

Available SM handles:
- Twitter: `@pythonexpress`
- Others: NA

Let me know if anything else is needed.

**Comment by iamaravindsekar** [comment]
This task is done, @Amritha-Madam @bpkapkar you can find the graphical creatives on the excel sheet..

**Comment by bkamapantula** [comment]
Closing this as we did the announcement. Thanks everyone.
