### ISSUE TITLE
Create Poster presentation announcement

### ISSUE THREAD

**Issue by soumendrak** [pythonindia/inpycon2023-tasks#60]
Post modification to the descriptions of [Poster 2023](https://in.pycon.org/cfp/posters-2023/proposals/), we need to make announcements for the Poster presentation.

**Comment by soumendrak** [comment]
Blocked by #53

**Comment by bpkapkar** [comment]
Hello All, Call for BoFs & Poster Presentation is posted on all of our SM channels. Do spread the word by liking and retweeting.

Twitter - https://twitter.com/pyconindia/status/1679347484395704320?t=MNPWtSh0txhp-_zkkU6F6Q&s=19

LinkedIn - https://www.linkedin.com/posts/pyconindia_pyconind2023-callforproposals-pythoncommunity-activity-7085114059284512769-Dufk?utm_source=share&utm_medium=member_android

Facebook - https://m.facebook.com/story.php?story_fbid=pfbid06qqzAM11wN4xhVKAHVo6yVJj8HDi7tbKdiPZB9NEbPc7CSMj7Y2w5AHuNugMoumbl&id=100064696716190&mibextid=Nif5oz

Instagram - https://www.instagram.com/p/Cun-hcLrBtp/?igshid=MzRlODBiNWFlZA==
